<?php

return [
    'medical' => [
        'user' => [
            'name' => 'Dr. Sarah Johnson',
            'desig' => 'Cardiologist & Heart Specialist',
            'mobile' => '+91 98765 43210',
            'email' => 'dr.sarah@heartcare.com',
            'city' => 'Mumbai',
            'state' => 'Maharashtra',
            'address' => 'HeartCare Clinic, Andheri West',
            'website' => 'https://heartcareclinic.com',
            'about' => 'Board-certified Cardiologist with 15+ years of experience in treating heart conditions. Specialized in interventional cardiology and preventive heart care.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'MBBS', 'desc' => 'All India Institute of Medical Sciences, New Delhi (2005)'],
            (object)['id' => 2, 'title' => 'MD Cardiology', 'desc' => 'Fortis Medical College, Mumbai (2008)'],
            (object)['id' => 3, 'title' => 'Fellowship', 'desc' => 'Fellowship in Interventional Cardiology, USA (2010)'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'Cardiac Surgery', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Heart Transplant Consultation', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Interventional Cardiology', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Preventive Cardiology', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/dr.sarahjohnson',
            'instagram' => 'https://instagram.com/dr.sarahcardio',
            'linkedin' => 'https://linkedin.com/in/sarahjohnson',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876543210',
            'map' => 'https://maps.google.com/?q=HeartCare+Clinic+Andheri+Mumbai',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'creative' => [
        'user' => [
            'name' => 'Alex Morrison',
            'desig' => 'Wedding & Event Photographer',
            'mobile' => '+91 98765 12345',
            'email' => 'alex@morrisonphotography.com',
            'city' => 'Bangalore',
            'state' => 'Karnataka',
            'address' => 'Koramangala, Bangalore',
            'website' => 'https://morrisonphotography.com',
            'about' => 'Professional photographer specializing in weddings, events, and portraits. Capturing your precious moments with artistic vision and creativity.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'Diploma in Photography', 'desc' => 'National Institute of Photography (2015)'],
            (object)['id' => 2, 'title' => 'Certified Wedding Photographer', 'desc' => 'WPPI Certified (2017)'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'Wedding Photography', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Event Coverage', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Portrait Photography', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Commercial Photography', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/morrisonphotography',
            'instagram' => 'https://instagram.com/morrison_captures',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => 'https://youtube.com/@morrisonphotography',
            'whatsapp' => '919812345678',
            'map' => 'https://maps.google.com/?q=Morrison+Photography+Koramangala+Bangalore',
        ],
        'portfolios' => [
            (object)['id' => 1, 'title' => 'Destination Wedding - Goa', 'desc' => 'Beautiful beach wedding captured at sunset', 'image' => null],
            (object)['id' => 2, 'title' => 'Corporate Event - Tech Summit', 'desc' => 'Professional event coverage for 1000+ attendees', 'image' => null],
            (object)['id' => 3, 'title' => 'Fashion Shoot - Spring Collection', 'desc' => 'Editorial photoshoot for leading fashion brand', 'image' => null],
        ],
        'thoughts' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'service' => [
        'user' => [
            'name' => 'Quick Fix Services',
            'desig' => 'Home Repair & Maintenance Experts',
            'mobile' => '+91 98765 00000',
            'email' => 'contact@quickfixservices.com',
            'city' => 'Delhi',
            'state' => 'Delhi',
            'address' => 'Lajpat Nagar, New Delhi',
            'website' => 'https://quickfixservices.com',
            'about' => 'Professional home repair and maintenance services. Plumbing, electrical, carpentry, painting, and more. Available 24/7 for emergency services.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'Licensed Contractor', 'desc' => 'Delhi Licensed Contractor #12345 (2018)'],
            (object)['id' => 2, 'title' => 'ISO Certified', 'desc' => 'ISO 9001:2015 Certified Company'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'Plumbing Services', 'desc' => 'All types of plumbing repairs and installations'],
            (object)['id' => 2, 'title' => 'Electrical Work', 'desc' => 'Licensed electricians for residential and commercial'],
            (object)['id' => 3, 'title' => 'Carpentry & Furniture', 'desc' => 'Custom furniture and repair services'],
            (object)['id' => 4, 'title' => 'Painting & Waterproofing', 'desc' => 'Interior and exterior painting solutions'],
            (object)['id' => 5, 'title' => 'AC Repair & Service', 'desc' => 'All brands AC installation and maintenance'],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/quickfixservices',
            'instagram' => null,
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919123456789',
            'map' => 'https://maps.google.com/?q=Quick+Fix+Services+Lajpat+Nagar+Delhi',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'manufacturing' => [
        'user' => [
            'name' => 'Prime Steel Industries',
            'desig' => 'Steel Manufacturing & Fabrication',
            'mobile' => '+91 98000 11111',
            'email' => 'sales@primesteel.com',
            'city' => 'Pune',
            'state' => 'Maharashtra',
            'address' => 'MIDC Industrial Area, Pune',
            'website' => 'https://primesteel.com',
            'about' => 'Leading manufacturer of steel products and fabrication services. ISO certified with 25+ years of industry experience. Serving construction, automotive, and industrial sectors.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'ISO 9001:2015', 'desc' => 'Quality Management System Certified'],
            (object)['id' => 2, 'title' => 'BIS Certified', 'desc' => 'Bureau of Indian Standards Approved'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'TMT Bars & Rods', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Steel Beams & Columns', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Custom Fabrication', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Industrial Structures', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => null,
            'linkedin' => 'https://linkedin.com/company/primesteel',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919800011111',
            'map' => 'https://maps.google.com/?q=Prime+Steel+Industries+MIDC+Pune',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [
            (object)['id' => 1, 'title' => 'TMT Bars (Fe 500)', 'desc' => 'High strength TMT bars for construction', 'image' => null, 'price' => '52000'],
            (object)['id' => 2, 'title' => 'Steel Beams', 'desc' => 'I-beams and H-beams for structural use', 'image' => null, 'price' => '65000'],
        ],
    ],

    'retail' => [
        'user' => [
            'name' => 'Fashion Hub',
            'desig' => 'Trendy Clothing & Accessories Store',
            'mobile' => '+91 98765 22222',
            'email' => 'info@fashionhub.com',
            'city' => 'Jaipur',
            'state' => 'Rajasthan',
            'address' => 'MI Road, Jaipur',
            'website' => 'https://fashionhub.com',
            'about' => 'Your one-stop destination for latest fashion trends. Premium quality clothing, footwear, and accessories at affordable prices. Free home delivery available.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Men\'s Clothing', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Women\'s Wear', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Kids Fashion', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Accessories & Footwear', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/fashionhubjaipur',
            'instagram' => 'https://instagram.com/fashionhub_official',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876522222',
            'map' => 'https://maps.google.com/?q=Fashion+Hub+MI+Road+Jaipur',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [
            (object)['id' => 1, 'title' => 'Designer Kurta Set', 'desc' => 'Premium cotton kurta with dupatta', 'image' => null, 'price' => '2499'],
            (object)['id' => 2, 'title' => 'Casual T-Shirts', 'desc' => 'Comfortable cotton t-shirts', 'image' => null, 'price' => '499'],
            (object)['id' => 3, 'title' => 'Ethnic Jewelry', 'desc' => 'Traditional Rajasthani jewelry', 'image' => null, 'price' => '899'],
        ],
    ],

    'realestate' => [
        'user' => [
            'name' => 'Rajesh Kumar',
            'desig' => 'RERA Certified Real Estate Consultant',
            'mobile' => '+91 98765 33333',
            'email' => 'rajesh@primerealty.com',
            'city' => 'Gurgaon',
            'state' => 'Haryana',
            'address' => 'DLF Phase 2, Gurgaon',
            'website' => 'https://primerealty.com',
            'about' => 'Experienced real estate consultant with 10+ years in property buying, selling, and leasing. Specialized in residential and commercial properties in NCR region.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'RERA Certified', 'desc' => 'RERA Registration #A12345678'],
            (object)['id' => 2, 'title' => 'MBA Real Estate', 'desc' => 'IIPM New Delhi (2012)'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'Property Buying', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Property Selling', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Rental Services', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Commercial Leasing', 'desc' => ''],
            (object)['id' => 5, 'title' => 'Property Valuation', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/rajeshkumar.realty',
            'instagram' => null,
            'linkedin' => 'https://linkedin.com/in/rajeshkumar-realty',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876533333',
            'map' => 'https://maps.google.com/?q=Prime+Realty+DLF+Gurgaon',
        ],
        'thoughts' => [],
        'portfolios' => [
            (object)['id' => 1, 'title' => '3 BHK Luxury Apartment - DLF', 'desc' => '2500 sq ft, Ready to move', 'image' => null],
            (object)['id' => 2, 'title' => 'Commercial Office Space', 'desc' => '5000 sq ft in Cyber City', 'image' => null],
        ],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'entertainment' => [
        'user' => [
            'name' => 'Priya Sharma',
            'desig' => 'Actor & Model',
            'mobile' => '+91 98765 44444',
            'email' => 'priya@talents.com',
            'city' => 'Mumbai',
            'state' => 'Maharashtra',
            'address' => 'Andheri West, Mumbai',
            'website' => 'https://priyasharma.com',
            'about' => 'Professional actor and model with experience in TV commercials, web series, and fashion shows. Available for ad shoots, ramp walks, and acting projects.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'Acting Diploma', 'desc' => 'Barry John Acting Studio, Mumbai (2018)'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'TV Commercials', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Fashion Modeling', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Web Series', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Ramp Walking', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/priyasharmaofficial',
            'instagram' => 'https://instagram.com/priya_sharma',
            'linkedin' => null,
            'twitter' => 'https://twitter.com/priya_sharma',
            'youtube' => null,
            'whatsapp' => '919876544444',
            'map' => 'https://maps.google.com/?q=Priya+Sharma+Andheri+West+Mumbai',
        ],
        'thoughts' => [],
        'portfolios' => [
            (object)['id' => 1, 'title' => 'Brand Commercial - Fashion Week', 'desc' => 'Lakme Fashion Week 2023', 'image' => null],
            (object)['id' => 2, 'title' => 'Web Series - Digital Platform', 'desc' => 'Lead role in drama series', 'image' => null],
        ],
        'videos' => [
            (object)['id' => 1, 'title' => 'Showreel 2024', 'url' => 'https://youtube.com/watch?v=dQw4w9WgXcQ'],
        ],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'production' => [
        'user' => [
            'name' => 'Cinematic Studios',
            'desig' => 'Film & Video Production House',
            'mobile' => '+91 98765 55555',
            'email' => 'contact@cinematicstudios.com',
            'city' => 'Hyderabad',
            'state' => 'Telangana',
            'address' => 'Jubilee Hills, Hyderabad',
            'website' => 'https://cinematicstudios.com',
            'about' => 'Award-winning production house specializing in corporate films, documentaries, music videos, and commercial ads. State-of-the-art equipment and experienced crew.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Corporate Films', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Documentaries', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Music Videos', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Commercial Ads', 'desc' => ''],
            (object)['id' => 5, 'title' => 'Short Films', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/cinematicstudios',
            'instagram' => 'https://instagram.com/cinematic_studios',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => 'https://youtube.com/@cinematicstudios',
            'whatsapp' => '919876555555',
            'map' => 'https://maps.google.com/?q=Cinematic+Studios+Jubilee+Hills+Hyderabad',
        ],
        'thoughts' => [],
        'portfolios' => [
            (object)['id' => 1, 'title' => 'Corporate Film - Tech Giant', 'desc' => 'Product launch video for Fortune 500 company', 'image' => null],
            (object)['id' => 2, 'title' => 'Music Video - Independent Artist', 'desc' => '5M+ views on YouTube', 'image' => null],
        ],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'multiservice' => [
        'user' => [
            'name' => 'Urban Services Pro',
            'desig' => 'Multi-Service Provider',
            'mobile' => '+91 98765 66666',
            'email' => 'info@urbanservicespro.com',
            'city' => 'Kolkata',
            'state' => 'West Bengal',
            'address' => 'Salt Lake, Kolkata',
            'website' => 'https://urbanservicespro.com',
            'about' => 'One-stop solution for all your home and office needs. Cleaning, pest control, security, IT support, logistics, and more. Trusted by 5000+ customers.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Housekeeping & Cleaning', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Pest Control Services', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Security Services', 'desc' => ''],
            (object)['id' => 4, 'title' => 'IT Support & Networking', 'desc' => ''],
            (object)['id' => 5, 'title' => 'Logistics & Transport', 'desc' => ''],
            (object)['id' => 6, 'title' => 'Event Management', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/urbanservicespro',
            'instagram' => null,
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876566666',
            'map' => 'https://maps.google.com/?q=Urban+Services+Pro+Salt+Lake+Kolkata',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'luxury' => [
        'user' => [
            'name' => 'Royal Jewels',
            'desig' => 'Fine Jewelry & Precious Gems',
            'mobile' => '+91 98765 77777',
            'email' => 'contact@royaljewels.com',
            'city' => 'Surat',
            'state' => 'Gujarat',
            'address' => 'Ring Road, Surat',
            'website' => 'https://royaljewels.com',
            'about' => 'Premium jewelry boutique offering exquisite diamond, gold, and platinum jewelry. Certified gemstones and custom design services. Trusted since 1985.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [
            (object)['id' => 1, 'title' => 'GIA Certified', 'desc' => 'Gemological Institute of America'],
            (object)['id' => 2, 'title' => 'BIS Hallmarked', 'desc' => 'All gold jewelry BIS certified'],
        ],
        'professions' => [
            (object)['id' => 1, 'title' => 'Diamond Jewelry', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Gold Collections', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Platinum Range', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Custom Design', 'desc' => ''],
            (object)['id' => 5, 'title' => 'Bridal Jewelry', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/royaljewels',
            'instagram' => 'https://instagram.com/royaljewels_official',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876577777',
            'map' => 'https://maps.google.com/?q=Royal+Jewels+Ring+Road+Surat',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [
            (object)['id' => 1, 'title' => 'Diamond Necklace Set', 'desc' => '18K gold with certified diamonds', 'image' => null, 'price' => '250000'],
            (object)['id' => 2, 'title' => 'Gold Chain', 'desc' => '22K hallmarked gold chain', 'image' => null, 'price' => '45000'],
        ],
    ],

    'technology' => [
        'user' => [
            'name' => 'CodeCraft Solutions',
            'desig' => 'Software Development & IT Services',
            'mobile' => '+91 98765 88888',
            'email' => 'hello@codecraftsolutions.com',
            'city' => 'Bangalore',
            'state' => 'Karnataka',
            'address' => 'Whitefield, Bangalore',
            'website' => 'https://codecraftsolutions.com',
            'about' => 'Leading IT solutions company specializing in web development, mobile apps, cloud services, and digital transformation. Serving startups to enterprises globally.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Web Development', 'desc' => 'React, Laravel, Node.js'],
            (object)['id' => 2, 'title' => 'Mobile Apps', 'desc' => 'iOS & Android development'],
            (object)['id' => 3, 'title' => 'Cloud Services', 'desc' => 'AWS, Azure, Google Cloud'],
            (object)['id' => 4, 'title' => 'DevOps & CI/CD', 'desc' => ''],
            (object)['id' => 5, 'title' => 'AI/ML Solutions', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => null,
            'linkedin' => 'https://linkedin.com/company/codecraftsolutions',
            'twitter' => 'https://twitter.com/codecraft_dev',
            'youtube' => null,
            'whatsapp' => '919876588888',
            'map' => 'https://maps.google.com/?q=CodeCraft+Solutions+Whitefield+Bangalore',
        ],
        'thoughts' => [],
        'portfolios' => [
            (object)['id' => 1, 'title' => 'E-commerce Platform', 'desc' => 'Built for 100K+ products', 'image' => null],
            (object)['id' => 2, 'title' => 'Healthcare App', 'desc' => 'Telemedicine platform with 50K users', 'image' => null],
        ],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'product' => [
        'user' => [
            'name' => 'TechGear India',
            'desig' => 'Smart Home & Electronics',
            'mobile' => '+91 98765 99999',
            'email' => 'sales@techgearindia.com',
            'city' => 'Ahmedabad',
            'state' => 'Gujarat',
            'address' => 'C.G. Road, Ahmedabad',
            'website' => 'https://techgearindia.com',
            'about' => 'Leading provider of smart home automation products and consumer electronics. Official distributor of top international brands. Nationwide delivery available.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Smart Home Devices', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Security Systems', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Audio & Video', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Home Automation', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/techgearindia',
            'instagram' => 'https://instagram.com/techgear_india',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => 'https://youtube.com/@techgearindia',
            'whatsapp' => '919876599999',
            'map' => 'https://maps.google.com/?q=TechGear+India+CG+Road+Ahmedabad',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [
            (object)['id' => 1, 'title' => 'Smart Door Lock', 'desc' => 'WiFi enabled with app control', 'image' => null, 'price' => '8999'],
            (object)['id' => 2, 'title' => 'Security Camera', 'desc' => '4K AI-powered CCTV', 'image' => null, 'price' => '12999'],
            (object)['id' => 3, 'title' => 'Smart Speaker', 'desc' => 'Voice assistant with premium sound', 'image' => null, 'price' => '4999'],
        ],
    ],

    'restaurant' => [
        'user' => [
            'name' => 'Spice Garden Restaurant',
            'desig' => 'Fine Dining & Multi-Cuisine',
            'mobile' => '+91 98765 10101',
            'email' => 'reservations@spicegarden.com',
            'city' => 'Chennai',
            'state' => 'Tamil Nadu',
            'address' => 'T. Nagar, Chennai',
            'website' => 'https://spicegarden.com',
            'about' => 'Award-winning multi-cuisine restaurant offering authentic Indian, Chinese, and Continental dishes. Perfect ambiance for family dinners and celebrations. Online reservations available.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [
            (object)['id' => 1, 'title' => 'Fine Dining', 'desc' => ''],
            (object)['id' => 2, 'title' => 'Home Delivery', 'desc' => ''],
            (object)['id' => 3, 'title' => 'Catering Services', 'desc' => ''],
            (object)['id' => 4, 'title' => 'Private Events', 'desc' => ''],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/spicegardenrestaurant',
            'instagram' => 'https://instagram.com/spicegarden_official',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876510101',
            'map' => 'https://maps.google.com/?q=Spice+Garden+Restaurant+T+Nagar+Chennai',
        ],
        'menuCategories' => [
            (object)[
                'id' => 1,
                'name' => 'Starters',
                'description' => 'Delicious appetizers to begin your meal',
                'is_active' => 1,
                'items' => [
                    (object)[
                        'id' => 1,
                        'name' => 'Paneer Tikka',
                        'description' => 'Grilled cottage cheese with Indian spices',
                        'price' => '299',
                        'dietary_type' => 'veg',
                        'is_bestseller' => 1,
                        'is_available' => 1,
                    ],
                    (object)[
                        'id' => 2,
                        'name' => 'Chicken Wings',
                        'description' => 'Crispy fried chicken wings with special sauce',
                        'price' => '349',
                        'dietary_type' => 'non-veg',
                        'is_bestseller' => 0,
                        'is_available' => 1,
                    ],
                ],
            ],
            (object)[
                'id' => 2,
                'name' => 'Main Course',
                'description' => 'Our signature dishes',
                'is_active' => 1,
                'items' => [
                    (object)[
                        'id' => 3,
                        'name' => 'Butter Chicken',
                        'description' => 'Tender chicken in rich tomato gravy',
                        'price' => '449',
                        'dietary_type' => 'non-veg',
                        'is_bestseller' => 1,
                        'is_available' => 1,
                    ],
                    (object)[
                        'id' => 4,
                        'name' => 'Palak Paneer',
                        'description' => 'Spinach curry with cottage cheese',
                        'price' => '329',
                        'dietary_type' => 'veg',
                        'is_bestseller' => 0,
                        'is_available' => 1,
                    ],
                ],
            ],
            (object)[
                'id' => 3,
                'name' => 'Desserts',
                'description' => 'Sweet endings to your meal',
                'is_active' => 1,
                'items' => [
                    (object)[
                        'id' => 5,
                        'name' => 'Gulab Jamun',
                        'description' => 'Traditional Indian sweet in sugar syrup',
                        'price' => '129',
                        'dietary_type' => 'veg',
                        'is_bestseller' => 1,
                        'is_available' => 1,
                    ],
                ],
            ],
        ],
        'restaurantInfo' => (object)[
            'opening_hours' => '11:00 AM - 11:00 PM',
            'cuisine_type' => 'Indian, Chinese, Continental',
            'seating_capacity' => '80',
            'average_cost' => '800',
            'delivery_available' => true,
            'reservation_available' => true,
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'political' => [
        'user' => [
            'name' => 'Aarav Singh',
            'desig' => 'Member of Legislative Assembly',
            'mobile' => '+91 98765 12121',
            'email' => 'office@aaravsingh.in',
            'city' => 'Lucknow',
            'state' => 'Uttar Pradesh',
            'address' => 'Ward Office, Hazratganj, Lucknow',
            'website' => 'https://aaravsingh.in',
            'about' => 'Committed public servant focused on infrastructure, education, and healthcare in the constituency.',
            'profile' => null,
            'banner' => null,
        ],
        'politicalProfile' => (object)[
            'party_name' => 'People First Party',
            'constituency' => 'Lucknow Central',
            'role_title' => 'MLA',
            'biography' => 'Serving the community with a focus on civic development, transparency, and inclusive growth.',
            'achievements' => [
                'Road and drainage upgrades across 12 wards',
                'Scholarship program for 1,200+ students',
                'Monthly health camps across the constituency',
            ],
        ],
        'publicServices' => [
            (object)['service_name' => 'Ration Card Assistance', 'description' => 'Help with new applications and corrections.'],
            (object)['service_name' => 'Pension Support', 'description' => 'Guidance on old-age pension and disability support.'],
            (object)['service_name' => 'Employment Helpdesk', 'description' => 'Job referrals and skill training enrollment.'],
        ],
        'developmentProjects' => [
            (object)['project_name' => 'Community Center Renovation', 'description' => 'Upgraded facilities for local events and training.'],
            (object)['project_name' => 'Smart Street Lighting', 'description' => 'LED lighting installed in key public areas.'],
        ],
        'publicEvents' => [
            (object)['event_title' => 'Public Hearing', 'event_date' => now(), 'description' => 'Open forum for grievances and suggestions.'],
            (object)['event_title' => 'Youth Employment Drive', 'event_date' => now()->addDays(10), 'description' => 'Career guidance and placements.'],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/aaravsinghofficial',
            'instagram' => 'https://instagram.com/aaravsingh',
            'linkedin' => 'https://linkedin.com/in/aaravsingh',
            'twitter' => 'https://twitter.com/aaravsingh',
            'youtube' => null,
            'whatsapp' => '919876512121',
            'map' => 'https://maps.google.com/?q=Hazratganj+Lucknow',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'interior' => [
        'user' => [
            'name' => 'Aria Interiors',
            'desig' => 'Interior Designer',
            'mobile' => '+91 98765 20202',
            'email' => 'hello@ariainteriors.com',
            'city' => 'Pune',
            'state' => 'Maharashtra',
            'address' => 'Koregaon Park, Pune',
            'website' => 'https://ariainteriors.com',
            'about' => 'Creating elegant, functional interiors with a focus on timeless design.',
            'profile' => null,
            'banner' => null,
        ],
        'interiorServices' => [
            (object)['service_name' => 'Residential Design', 'description' => 'Complete home interiors with turnkey execution.'],
            (object)['service_name' => 'Commercial Spaces', 'description' => 'Office and retail layouts with brand focus.'],
            (object)['service_name' => '3D Visualization', 'description' => 'Photorealistic renders and walkthroughs.'],
        ],
        'interiorProjects' => [
            (object)['project_name' => 'Skyline Apartment', 'description' => '3BHK modern luxury interiors.'],
            (object)['project_name' => 'Nimbus Office', 'description' => 'Open office workspace and meeting zones.'],
        ],
        'interiorPortfolio' => [
            (object)['project_title' => 'Sunset Villa', 'project_description' => 'Warm modern villa with custom furniture.'],
            (object)['project_title' => 'Minimal Studio', 'project_description' => 'Space-optimized studio design.'],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/ariainteriors',
            'instagram' => 'https://instagram.com/ariainteriors',
            'linkedin' => 'https://linkedin.com/company/ariainteriors',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876520202',
            'map' => 'https://maps.google.com/?q=Koregaon+Park+Pune',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'education' => [
        'user' => [
            'name' => 'Bright Future Academy',
            'desig' => 'Coaching Institute',
            'mobile' => '+91 98765 30303',
            'email' => 'info@brightfutureacademy.com',
            'city' => 'Indore',
            'state' => 'Madhya Pradesh',
            'address' => 'Palasia, Indore',
            'website' => 'https://brightfutureacademy.com',
            'about' => 'Focused coaching for competitive exams with experienced faculty and structured learning plans.',
            'profile' => null,
            'banner' => null,
        ],
        'educationCourses' => [
            (object)[
                'course_name' => 'Foundation Program',
                'class_standard' => 'Class 9-10',
                'board_exam' => 'CBSE',
                'mode' => 'offline',
                'duration_months' => 10,
                'fee_structure' => '12,000 per term',
                'description' => 'Strong academic base with weekly tests and doubt sessions.',
            ],
            (object)[
                'course_name' => 'JEE Main Crash Course',
                'class_standard' => 'Class 12',
                'board_exam' => 'JEE',
                'mode' => 'hybrid',
                'duration_months' => 4,
                'fee_structure' => '18,000 total',
                'description' => 'Revision focused modules with daily practice sheets.',
            ],
            (object)[
                'course_name' => 'NEET Prep',
                'class_standard' => 'Class 11-12',
                'board_exam' => 'NEET',
                'mode' => 'offline',
                'duration_months' => 12,
                'fee_structure' => '45,000 total',
                'description' => 'Concept clarity, test series, and mentorship.',
            ],
        ],
        'educationFaculty' => [
            (object)['faculty_name' => 'Dr. Kavita Sharma', 'qualification' => 'PhD Physics', 'specialization' => 'Mechanics'],
            (object)['faculty_name' => 'Amit Verma', 'qualification' => 'MSc Chemistry', 'specialization' => 'Organic Chemistry'],
            (object)['faculty_name' => 'Neha Singh', 'qualification' => 'MSc Mathematics', 'specialization' => 'Calculus'],
        ],
        'educationResults' => [
            (object)['exam_type' => 'JEE Main', 'exam_year' => '2025', 'pass_percentage' => 92.5, 'total_students' => 120],
            (object)['exam_type' => 'NEET', 'exam_year' => '2025', 'pass_percentage' => 89.2, 'total_students' => 90],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/brightfutureacademy',
            'instagram' => 'https://instagram.com/brightfutureacademy',
            'linkedin' => 'https://linkedin.com/company/brightfutureacademy',
            'twitter' => null,
            'youtube' => 'https://youtube.com/@brightfutureacademy',
            'whatsapp' => '919876530303',
            'map' => 'https://maps.google.com/?q=Palasia+Indore',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'solar' => [
        'user' => [
            'name' => 'SunRise Solar',
            'desig' => 'Solar EPC & Energy Solutions',
            'mobile' => '+91 98765 40404',
            'email' => 'hello@sunrisesolar.com',
            'city' => 'Surat',
            'state' => 'Gujarat',
            'address' => 'Ring Road, Surat',
            'website' => 'https://sunrisesolar.com',
            'about' => 'Trusted solar EPC partner for residential and commercial rooftops. We design, install, and maintain high-efficiency solar plants with transparent pricing.',
            'profile' => null,
            'banner' => null,
        ],
        'solarSolutions' => [
            (object)[
                'solution_name' => 'Residential Rooftop 3kW',
                'solution_type' => 'residential',
                'system_capacity_kw' => 3,
                'price_per_kw' => 52000,
                'total_price' => 156000,
                'warranty_years' => 25,
                'components' => ['Mono PERC panels', 'Hybrid inverter', 'Mounting structure'],
                'features' => ['Net metering ready', 'Mobile monitoring', '5-year service support'],
                'description' => 'Ideal for 2-3 BHK homes with monthly consumption up to 400 units.',
            ],
            (object)[
                'solution_name' => 'Commercial 20kW System',
                'solution_type' => 'commercial',
                'system_capacity_kw' => 20,
                'price_per_kw' => 48000,
                'total_price' => 960000,
                'warranty_years' => 25,
                'components' => ['Mono panels', 'String inverter', 'MC4 cabling'],
                'features' => ['High ROI', 'SCADA monitoring', 'Rapid installation'],
                'description' => 'Optimized for retail and small industrial facilities.',
            ],
            (object)[
                'solution_name' => 'Industrial 100kW Plant',
                'solution_type' => 'industrial',
                'system_capacity_kw' => 100,
                'price_per_kw' => 45000,
                'total_price' => 4500000,
                'warranty_years' => 25,
                'components' => ['High wattage panels', 'Central inverter', 'HT cabling'],
                'features' => ['PR guarantee', 'Remote O&M', 'Energy audits included'],
                'description' => 'Large-scale installation with turnkey project execution.',
            ],
        ],
        'solarProjects' => [
            (object)[
                'client_name' => 'Apex Textiles',
                'system_type' => 'On-Grid',
                'capacity_kw' => 50,
                'location' => 'Sachin GIDC',
                'project_status' => 'commissioned',
                'net_amount' => 2200000,
                'commissioning_date' => now()->subDays(40),
            ],
            (object)[
                'client_name' => 'Green Heights Society',
                'system_type' => 'Hybrid',
                'capacity_kw' => 15,
                'location' => 'Vesu',
                'project_status' => 'installation',
                'net_amount' => 720000,
                'commissioning_date' => now()->addDays(15),
            ],
        ],
        'solarMonitoring' => [
            (object)[
                'monitoring_platform' => 'https://monitor.sunrisesolar.com/plant-01',
                'daily_generation_kwh' => 260,
                'monthly_generation_kwh' => 7800,
                'performance_ratio' => 0.82,
                'system_uptime_percentage' => 99.2,
                'alerts' => ['Inverter firmware update due'],
                'last_updated' => now(),
            ],
        ],
        'solarAmc' => [
            (object)[
                'amc_type' => 'premium',
                'amc_amount' => 12000,
                'visit_frequency' => 'monthly',
                'amc_end_date' => now()->addMonths(10),
                'services_included' => ['Panel cleaning', 'Inverter health check', 'Performance optimization'],
                'next_visit_date' => now()->addDays(20),
            ],
        ],
        'solarSubsidies' => [
            (object)[
                'scheme_name' => 'PM Surya Ghar',
                'status' => 'approved',
                'subsidy_amount' => 78000,
                'application_number' => 'PSG-2026-1120',
            ],
        ],
        'social' => (object)[
            'facebook' => 'https://facebook.com/sunrisesolar',
            'instagram' => 'https://instagram.com/sunrisesolar',
            'linkedin' => 'https://linkedin.com/company/sunrisesolar',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876540404',
            'map' => 'https://maps.google.com/?q=SunRise+Solar+Surat',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'ca' => [
        'user' => [
            'name' => 'Verma & Co.',
            'desig' => 'Chartered Accountants',
            'mobile' => '+91 98765 50505',
            'email' => 'contact@vermaandco.in',
            'city' => 'Delhi',
            'state' => 'Delhi',
            'address' => 'Connaught Place, New Delhi',
            'website' => 'https://vermaandco.in',
            'about' => 'Experienced CA firm providing taxation, GST, audit, and compliance services for individuals and businesses.',
            'profile' => null,
            'banner' => null,
        ],
        'caServices' => [
            (object)[
                'service_category' => 'taxation',
                'service_name' => 'Income Tax Return Filing',
                'pricing_type' => 'fixed',
                'base_price' => 1500,
                'turnaround_time_days' => 3,
                'required_documents' => ['PAN', 'Form 16', 'Bank statement'],
                'description' => 'ITR filing for salaried and self-employed clients.',
            ],
            (object)[
                'service_category' => 'gst',
                'service_name' => 'GST Return Filing',
                'pricing_type' => 'monthly',
                'base_price' => 2500,
                'turnaround_time_days' => 2,
                'required_documents' => ['GSTIN', 'Sales invoices', 'Purchase invoices'],
                'description' => 'GSTR-1, GSTR-3B and annual return support.',
            ],
            (object)[
                'service_category' => 'audit',
                'service_name' => 'Tax Audit',
                'pricing_type' => 'project_based',
                'base_price' => 25000,
                'turnaround_time_days' => 10,
                'required_documents' => ['Books of accounts', 'Bank statements'],
                'description' => 'Statutory and tax audit services for businesses.',
            ],
        ],
        'caCases' => [
            (object)[
                'client_name' => 'Aarav Enterprises',
                'financial_year' => '2025-26',
                'case_status' => 'in_progress',
                'case_notes' => 'Awaiting additional invoices.',
            ],
        ],
        'caConsultations' => [
            (object)[
                'client_name' => 'Neha Gupta',
                'consultation_type' => 'video',
                'appointment_date' => now()->addDays(2),
                'appointment_time' => '4:00 PM',
                'payment_status' => 'paid',
                'status' => 'scheduled',
            ],
        ],
        'caDeadlines' => [
            (object)[
                'compliance_type' => 'ITR',
                'financial_year' => '2025-26',
                'due_date' => now()->addDays(45),
                'status' => 'pending',
                'reminder_sent' => false,
            ],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => 'https://instagram.com/vermaandco',
            'linkedin' => 'https://linkedin.com/company/vermaandco',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876550505',
            'map' => 'https://maps.google.com/?q=Connaught+Place+New+Delhi',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'accountant' => [
        'user' => [
            'name' => 'Verma & Co.',
            'desig' => 'Chartered Accountants',
            'mobile' => '+91 98765 50505',
            'email' => 'contact@vermaandco.in',
            'city' => 'Delhi',
            'state' => 'Delhi',
            'address' => 'Connaught Place, New Delhi',
            'website' => 'https://vermaandco.in',
            'about' => 'Experienced CA firm providing taxation, GST, audit, and compliance services for individuals and businesses.',
            'profile' => null,
            'banner' => null,
        ],
        'caServices' => [
            (object)[
                'service_category' => 'taxation',
                'service_name' => 'Income Tax Return Filing',
                'pricing_type' => 'fixed',
                'base_price' => 1500,
                'turnaround_time_days' => 3,
                'required_documents' => ['PAN', 'Form 16', 'Bank statement'],
                'description' => 'ITR filing for salaried and self-employed clients.',
            ],
            (object)[
                'service_category' => 'gst',
                'service_name' => 'GST Return Filing',
                'pricing_type' => 'monthly',
                'base_price' => 2500,
                'turnaround_time_days' => 2,
                'required_documents' => ['GSTIN', 'Sales invoices', 'Purchase invoices'],
                'description' => 'GSTR-1, GSTR-3B and annual return support.',
            ],
            (object)[
                'service_category' => 'audit',
                'service_name' => 'Tax Audit',
                'pricing_type' => 'project_based',
                'base_price' => 25000,
                'turnaround_time_days' => 10,
                'required_documents' => ['Books of accounts', 'Bank statements'],
                'description' => 'Statutory and tax audit services for businesses.',
            ],
        ],
        'caCases' => [
            (object)[
                'client_name' => 'Aarav Enterprises',
                'financial_year' => '2025-26',
                'case_status' => 'in_progress',
                'case_notes' => 'Awaiting additional invoices.',
            ],
        ],
        'caConsultations' => [
            (object)[
                'client_name' => 'Neha Gupta',
                'consultation_type' => 'video',
                'appointment_date' => now()->addDays(2),
                'appointment_time' => '4:00 PM',
                'payment_status' => 'paid',
                'status' => 'scheduled',
            ],
        ],
        'caDeadlines' => [
            (object)[
                'compliance_type' => 'ITR',
                'financial_year' => '2025-26',
                'due_date' => now()->addDays(45),
                'status' => 'pending',
                'reminder_sent' => false,
            ],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => 'https://instagram.com/vermaandco',
            'linkedin' => 'https://linkedin.com/company/vermaandco',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876550505',
            'map' => 'https://maps.google.com/?q=Connaught+Place+New+Delhi',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'astrologer' => [
        'user' => [
            'name' => 'Cosmic Vastu Studio',
            'desig' => 'Astrologer & Vastu Consultant',
            'mobile' => '+91 98765 60606',
            'email' => 'hello@cosmicvastu.in',
            'city' => 'Jaipur',
            'state' => 'Rajasthan',
            'address' => 'C-Scheme, Jaipur',
            'website' => 'https://cosmicvastu.in',
            'about' => 'Personalized astrology and vastu guidance with 12+ years of experience. Online and in-person consultations available.',
            'profile' => null,
            'banner' => null,
        ],
        'astroServices' => [
            (object)[
                'service_category' => 'astrology',
                'service_name' => 'Kundli Analysis',
                'consultation_duration_minutes' => 45,
                'consultation_fee' => 1200,
                'is_online_available' => true,
                'description' => 'Detailed birth chart analysis with personalized guidance.',
            ],
            (object)[
                'service_category' => 'vastu',
                'service_name' => 'Home Vastu Review',
                'consultation_duration_minutes' => 60,
                'consultation_fee' => 2000,
                'is_online_available' => true,
                'description' => 'Layout and energy audit with practical remedies.',
            ],
            (object)[
                'service_category' => 'tarot',
                'service_name' => 'Tarot Reading',
                'consultation_duration_minutes' => 30,
                'consultation_fee' => 800,
                'is_online_available' => true,
                'description' => 'Quick guidance on love, career, and finance.',
            ],
        ],
        'astroConsultations' => [
            (object)[
                'client_name' => 'Aditi Sharma',
                'consultation_mode' => 'video',
                'appointment_date' => now()->addDays(1),
                'appointment_time' => '6:30 PM',
                'status' => 'scheduled',
            ],
        ],
        'astroReports' => [
            (object)[
                'client_name' => 'Rahul Verma',
                'birth_date' => now()->subYears(29),
                'birth_place' => 'Udaipur',
            ],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => 'https://instagram.com/cosmicvastu',
            'linkedin' => null,
            'twitter' => null,
            'youtube' => 'https://youtube.com/@cosmicvastu',
            'whatsapp' => '919876560606',
            'map' => 'https://maps.google.com/?q=C-Scheme+Jaipur',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'security' => [
        'user' => [
            'name' => 'Shield Secure Systems',
            'desig' => 'CCTV & Security Solutions',
            'mobile' => '+91 98765 70707',
            'email' => 'support@shieldsecure.in',
            'city' => 'Mumbai',
            'state' => 'Maharashtra',
            'address' => 'Andheri East, Mumbai',
            'website' => 'https://shieldsecure.in',
            'about' => 'End-to-end security solutions including CCTV, access control, alarms, and AMC support.',
            'profile' => null,
            'banner' => null,
        ],
        'securityProducts' => [
            (object)[
                'product_category' => 'cctv',
                'product_name' => '4MP Dome Camera',
                'brand' => 'SecureCam',
                'model' => 'SC-4D',
                'price' => 4500,
                'specifications' => ['4MP resolution', 'IR night vision', 'IP67'],
                'description' => 'Indoor/outdoor dome camera with night vision.',
            ],
            (object)[
                'product_category' => 'access_control',
                'product_name' => 'Biometric Attendance',
                'brand' => 'AccessPro',
                'model' => 'AP-200',
                'price' => 12000,
                'specifications' => ['Fingerprint + RFID', 'WiFi enabled'],
                'description' => 'Attendance and access control system.',
            ],
        ],
        'securitySurveys' => [
            (object)[
                'client_name' => 'Greenway Office',
                'property_type' => 'office',
                'survey_status' => 'scheduled',
                'area_sqft' => 3500,
            ],
        ],
        'securityProjects' => [
            (object)[
                'client_name' => 'Horizon Warehouse',
                'project_type' => 'cctv',
                'project_status' => 'installation',
                'location' => 'Bhiwandi',
                'total_amount' => 185000,
            ],
        ],
        'securityAmc' => [
            (object)[
                'amc_type' => 'premium',
                'visit_frequency' => 'quarterly',
                'amc_amount' => 15000,
                'next_visit_date' => now()->addDays(20),
            ],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => 'https://instagram.com/shieldsecure',
            'linkedin' => 'https://linkedin.com/company/shieldsecure',
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876570707',
            'map' => 'https://maps.google.com/?q=Andheri+East+Mumbai',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'influencer' => [
        'user' => [
            'name' => 'Aanya Verma',
            'desig' => 'Lifestyle & Fashion Creator',
            'mobile' => '+91 98765 80808',
            'email' => 'hello@aanyaverma.com',
            'city' => 'Mumbai',
            'state' => 'Maharashtra',
            'address' => 'Bandra West, Mumbai',
            'website' => 'https://aanyaverma.com',
            'about' => 'Content creator specializing in fashion, lifestyle, and travel. Open for brand collaborations and campaign partnerships.',
            'profile' => null,
            'banner' => null,
        ],
        'creatorStats' => [
            (object)[
                'platform' => 'instagram',
                'handle' => '@aanya.verma',
                'followers_count' => 265000,
                'avg_reach' => 98000,
                'avg_engagement_rate' => 8.2,
                'monthly_views' => 720000,
                'audience_demographics' => ['65% Female', '18-34 Age Group', 'Top Cities: Mumbai, Delhi', 'Primary Region: India'],
            ],
            (object)[
                'platform' => 'youtube',
                'handle' => 'Aanya Verma',
                'followers_count' => 142000,
                'avg_reach' => 54000,
                'avg_engagement_rate' => 6.4,
                'monthly_views' => 320000,
                'audience_demographics' => ['Lifestyle & vlogs', 'Audience: 18-30', 'Tier 1 cities'],
            ],
        ],
        'brandCollaborations' => [
            (object)[
                'brand_name' => 'Glow Beauty',
                'collaboration_type' => 'sponsored_post',
                'platform' => 'instagram',
                'status' => 'completed',
                'campaign_brief' => 'Summer skincare launch campaign with product reels.',
            ],
            (object)[
                'brand_name' => 'Urban Travel Co.',
                'collaboration_type' => 'review',
                'platform' => 'youtube',
                'status' => 'in_progress',
                'campaign_brief' => 'Hotel stay review and city guide vlog.',
            ],
        ],
        'creatorPortfolio' => [
            (object)[
                'content_type' => 'reel',
                'title' => 'Glow Beauty Reel',
                'brand_name' => 'Glow Beauty',
                'content_url' => 'https://instagram.com/p/sample',
                'views_count' => 180000,
                'engagement_rate' => 9.1,
                'description' => 'High-performing product launch reel.',
                'thumbnail' => null,
            ],
            (object)[
                'content_type' => 'video',
                'title' => 'Urban Travel Vlog',
                'brand_name' => 'Urban Travel Co.',
                'content_url' => 'https://youtube.com/watch?v=sample',
                'views_count' => 96000,
                'engagement_rate' => 7.4,
                'description' => 'City guide with hotel experience.',
                'thumbnail' => null,
            ],
        ],
        'social' => (object)[
            'facebook' => null,
            'instagram' => 'https://instagram.com/aanya.verma',
            'linkedin' => 'https://linkedin.com/in/aanyaverma',
            'twitter' => 'https://twitter.com/aanyaverma',
            'youtube' => 'https://youtube.com/@aanyaverma',
            'whatsapp' => '919876580808',
            'map' => 'https://maps.google.com/?q=Bandra+West+Mumbai',
        ],
        'qualifications' => [],
        'professions' => [],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],

    'default' => [
        'user' => [
            'name' => 'John Doe',
            'desig' => 'Professional',
            'mobile' => '+91 98765 00001',
            'email' => 'john@example.com',
            'city' => 'Mumbai',
            'state' => 'Maharashtra',
            'address' => 'Sample Address',
            'website' => 'https://example.com',
            'about' => 'Professional with expertise in my field. Providing quality services to clients.',
            'profile' => null,
            'banner' => null,
        ],
        'qualifications' => [],
        'professions' => [],
        'social' => (object)[
            'facebook' => null,
            'instagram' => null,
            'linkedin' => null,
            'twitter' => null,
            'youtube' => null,
            'whatsapp' => '919876500001',
            'map' => 'https://maps.google.com/?q=Sample+Location+Mumbai',
        ],
        'thoughts' => [],
        'portfolios' => [],
        'videos' => [],
        'professional_photos' => [],
        'myproducts' => [],
    ],
];
